.....

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -4,7 +4,7 @@ on:
     branches: [main, master]
   pull_request:
     branches: [main, master]
-  deployment_status:
+
 jobs:
   test-api:
     timeout-minutes: 15
@@ -42,6 +42,8 @@ jobs:
           overwrite: true
 
   merge-reports-and-upload:
+    permissions:
+      contents: read
     if: always()
     needs: [test-api]
     runs-on: ubuntu-latest
@@ -71,11 +73,18 @@ jobs:
           merge-multiple: true
 
       - name: List downloaded reports
-        run: ls -R playwright-report
+        run: |
+          ls -la playwright-report
+          find playwright-report -type f -name 'blob-report-*' -print
 
       # Merge the blobs into one single HTML report
       - name: Merge the blobs into one single HTML report
-        run: pnpm exec playwright merge-reports --reporter html playwright-report
+        run:
+          pnpm exec playwright merge-reports --reporter html playwright-report
+          if [ $? -ne 0 ]; then
+          echo "Error merging reports"
+          exit 1
+          fi
 
       # Upload full HTML report to artifacts for history
       - name: Upload full HTML report to artifacts for history
