function

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -79,11 +79,11 @@ jobs:
 
       # Merge the blobs into one single HTML report
       - name: Merge the blobs into one single HTML report
-        run:
+        run: |
           pnpm exec playwright merge-reports --reporter html playwright-report
           if [ $? -ne 0 ]; then
-          echo "Error merging reports"
-          exit 1
+            echo "Error merging reports"
+            exit 1
           fi
       # Upload full HTML report to artifacts for history
       - name: Upload full HTML report to artifacts for history
